version: "3"
services:

  backend:
    build: ./backend
    networks:
      - webnet
    ports:
      - "8080:8080"
    #volumes:
      #- shared:/shared

  frontend:
    build: ./frontend
    networks:
      - webnet
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API: //192.168.99.100:8080
    #volumes:
      #- shared:/shared

networks:
  webnet:

#volumes:
  #shared: